print('import math')
print('')
print('')
print('а) (1 + x) ** 2')
print('б) math.sqrt(1 + x ** 2)')
print('в) math.fabs(a + b * x)')
print('г) math.sin(8)')
print('д) math.pow(math.cos(x ** 3), 2')
print('е) math.tan(x)')
print('ж) math.log2(x / 5)')
print('з) math.cosh(x)')
print('и) math.atan(10 ** 3)')
print('к) math.asin(x)')
