print('import math')
print('')
print('')
print('а) x ** -1')
print('б) x ** 4')
print('в) x ** -2')
print('г) x ** 5')
print('д) x ** 100')
print('е) 2 ** (x + 1)')
print('ж) x ** math.sqrt(2)')
print('з) (1 + x) ** (1 / 3)')
